[package]
name = "etanol_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "etanol_utils"
path = "src/lib.rs"

[dependencies]
ansi_term = "0.12.1"